<?php

namespace Dbm\CmsLayouts\Model\ResourceModel\Cms;

use Magento\Framework\DB\Select;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use Zend_Db_Select;

/**
 * Class Collection
 * @package Dbm\CmsLayouts\Model\ResourceModel\Cms
 */
class Collection extends AbstractCollection
{
    /**
     * ID Field Name
     *
     * @var string
     */
    protected $_idFieldName = 'cms_id';

    /**
     * Event prefix
     *
     * @var string
     */
    protected $_eventPrefix = 'dbm_cmslayouts_cms_collection';

    /**
     * Event object
     *
     * @var string
     */
    protected $_eventObject = 'cms_collection';

    /**
     * Define resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Dbm\CmsLayouts\Model\Cms', 'Dbm\CmsLayouts\Model\ResourceModel\Cms');
    }

    /**
     * Get SQL for get record count.
     * Extra GROUP BY strip added.
     *
     * @return Select
     */
    public function getSelectCountSql()
    {
        $countSelect = parent::getSelectCountSql();
        $countSelect->reset(Zend_Db_Select::GROUP);

        return $countSelect;
    }

    /**
     * @param string $valueField
     * @param string $labelField
     * @param array $additional
     *
     * @return array
     */
    protected function _toOptionArray($valueField = 'cms_id', $labelField = 'name', $additional = [])
    {
        return parent::_toOptionArray($valueField, $labelField, $additional);
    }

    /**
     * @param array|string $field
     * @param null $condition
     *
     * @return AbstractCollection
     */
    public function addFieldToFilter($field, $condition = null)
    {
        if ($field === 'cms_id') {
            $field = 'main_table.cms_id';
        }

        if ($field === 'type' && isset($condition['like'])) {
            $condition['like'] = str_replace("'%", '', $condition['like']);
            $condition['like'] = str_replace("%'", '', $condition['like']);
            if (stripos('Image', $condition['like']) !== false) {
                $condition = 0;
            }
            if (stripos('Advanced', $condition['like']) !== false) {
                $condition = 1;
            }
        }

        if ($field === 'status' && isset($condition['like'])) {
            $condition['like'] = str_replace("'%", '', $condition['like']);
            $condition['like'] = str_replace("%'", '', $condition['like']);
            if (stripos('Enable', $condition['like']) !== false) {
                $condition = 1;
            }
            if (stripos('Disable', $condition['like']) !== false) {
                $condition = 0;
            }
        }

        return parent::addFieldToFilter($field, $condition); // TODO: Change the autogenerated stub
    }
}
